### ISSUE TITLE
[Feature Request] Make All People Named "Cannicide" Immune

### ISSUE THREAD

**Issue by Elvenide** [Kurumi78/NekoC#4]
Make all players named "Cannicide" immune to being a catgirl, as illustrated in the following professional graphic.

![image](https://github.com/Kurumi78/NekoC/assets/41762964/1098e5b5-3151-4149-89a3-902628fc402a)

**Comment by Kurumi78** [comment]
Declined, unfortunatly it is not within the scope of the plugin
