### ISSUE TITLE
/nekotf command does't work

### ISSUE THREAD

**Issue by dnchshrp** [Kurumi78/NekoC#6]
Hi! I love this plugin's idea, and always wanted something like this before! But I encountered a problem - the /nekotf command just doesn't work. It doesn't output anything in the chat or console and doesn't do anything. Could this happen because my server is running in offline mode?

Server software: Purpur 1.16.5
Java version: OpenJDK 21
Plugin list:
![image](https://github.com/Kurumi78/NekoC/assets/113385003/03cf8974-4b90-424e-aeaa-32ccc86ac9eb)

I'm using the latest version from spigotmc.org

**Comment by Kurumi78** [comment]
Have you given the proper permission NekoC.nekotf for people who should be able to use the command?

**Comment by dnchshrp** [comment]
Thank you, I gave the permission and now it works! :3
